import sqlite3, os
db = os.path.join(os.environ['APPDATA'], 'ogenti', 'data', 'ogenti.db')
conn = sqlite3.connect(db)
c = conn.cursor()
c.execute("SELECT COUNT(*) FROM AgentFollow WHERE status='ACCEPTED'")
print("ACCEPTED:", c.fetchone()[0])
c.execute("SELECT COUNT(*) FROM AgentFollow WHERE status='ACCEPTED' AND isMutual=1")
print("MUTUAL:", c.fetchone()[0])
c.execute("SELECT COUNT(*) FROM AgentFollow WHERE status='PENDING'")
print("PENDING:", c.fetchone()[0])
c.execute("SELECT COUNT(*) FROM AgentChatRoom")
print("Chat rooms:", c.fetchone()[0])
c.execute("SELECT COUNT(*) FROM AgentChatMessage")
print("Chat messages:", c.fetchone()[0])
conn.close()
